### ISSUE TITLE
'all_D47' plot titles hard to read

### ISSUE THREAD

**Issue by abjost** [noahtrawicki/blimp#1]
Graphs become difficult to read when there are a lot of samples. Also, sample names get cut off when they are over ~11 characters. Maybe you could increase the default graph width and have the length be set by the number of samples?

![all_D47](https://user-images.githubusercontent.com/51931193/123865558-0ad3ac00-d8fa-11eb-9555-4a12db5734f2.png)

**Comment by noahtrawicki** [comment]
Used plt.tightlayout() to fix ylabel cut off issue; used variable figure height for ylabel smushing. Thanks for the suggestions!

**Comment by abjost** [comment]
New version works well, though there is some dead space at the top/bottom of the plot and the spacing could be more economical. It's more functional, which is the important thing.

![all_D47](https://user-images.githubusercontent.com/51931193/124169366-2b277600-da74-11eb-8844-947ad18de685.png)
