### ISSUE TITLE
headers '95% CL' and '95% CL analysis' in summary.csv have spaces

### ISSUE THREAD

**Issue by abjost** [noahtrawicki/blimp#10]
Request that spaces be replaced with underscores because they don't import into R properly. Also, the % symbols don't import either, so they could be swapped with 'percent' instead if desired. Not sure if these are fringe R problems or more general.

**Comment by abjost** [comment]
You also might want to change the name so it's not led by a number. R and maybe other languages will not allow variables to start with numbers.  Any names led by numbers have Xs added to them automatically by R. E.g., 95 becomes X95. So the full issue ends up being '95% CL analysis' --> 'X95..CL.analysis' which is kinda clunky.

**Comment by noahtrawicki** [comment]
Good catch, thanks. Now these are "CL_95_pct" and "CL_95_pct_analysis". Will break some other scripts but will be better in the long run!
