### ISSUE TITLE
Include a separate script for processing single data files

### ISSUE THREAD

**Issue by abjost** [noahtrawicki/blimp#5]
This would be used for troubleshooting and checking for issues. Ideally, this script would plot cycle-by-cycle data for each of the m/z beams (for ref and samp), little deltas, big deltas, and d13C/d18O (not sure how you would calculate D47/d13C/d18O without ETH data, so if you can't just skip that part). The output could be 2-3 multipanel plots. If you can plot D47, it may also be useful to illustrate bad cycles on this plot, like your 'data vetting' script current does.

**Comment by noahtrawicki** [comment]
Could be improved but is in there.
